Repository AIX-Googley/CodeClimX, pull requests merged in 2024-03, with the labels that each got.

#10 [FEATURE] webSocket 연결과 프로젝트 기본 스트럭처
  .gitignore
  lib/chatbot/components/chatbot_widget.dart
  lib/chatbot/pages/chatbot_page.dart
  lib/community/something.dart
  lib/home/home_screen.dart
  lib/main.dart
  lib/quiz/something.dart
  lib/videos/something.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation

#13 동영상 커리큘럼 기능 구현 1차
  .gitignore
  android/.gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/.gitignore
  lib/home/home_screen.dart
  lib/router.dart
  lib/videos/authentication/birthday_screen.dart
  lib/videos/authentication/login_screen.dart
  lib/videos/authentication/password_screen.dart
  lib/videos/authentication/repos/authentication_repo.dart
  lib/videos/authentication/view_models/signup_view_model.dart
  lib/videos/curriculum/lecture_screen.dart
  lib/videos/curriculum/roadmap_screen.dart
  lib/videos/curriculum/topics_screen.dart
  lib/videos/curriculum/widgets/lecturebox.dart
  macos/.gitignore
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: documentation

#21 [FEATURE] chatbot 메세지 내역 firestore 저장
  .vscode/settings.json
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/chatbot/model/chat.dart
  lib/chatbot/pages/chatbot_page.dart
  lib/chatbot/service/database.dart
  pubspec.lock
Labels: enhancement

#35 로그인, 회원가입, 비디오 관련 화면 수정
  lib/videos/authentication/login_screen.dart
  lib/videos/authentication/sign_up_screen.dart
  lib/videos/curriculum/lecture_screen.dart
  lib/videos/curriculum/roadmap_screen.dart
  lib/videos/curriculum/topics_screen.dart
  lib/videos/curriculum/widgets/lecturebox.dart
Labels: design

#37 버그 수정
  lib/community/screens/question_detail_screen.dart
  lib/community/screens/question_screen.dart
  lib/community/widgets/question_list_tile.dart
  lib/home/home_screen.dart
  lib/main.dart
  lib/quiz/screens/quiz_detail_screen.dart
  lib/quiz/screens/quiz_result_screen.dart
  lib/videos/authentication/login_screen.dart
  lib/videos/something.dart
Labels: bug

#39 주관식 사용자 답변 피드백 프롬프트 수정
  lib/quiz/screens/descriptive_result_screen.dart
  lib/quiz/screens/quiz_detail_screen.dart
  lib/quiz/screens/quiz_screen.dart
  lib/quiz/services/gpt_service.dart
Labels: enhancement, design

#40 동영상 semantic search 기능 및 화면 추가
  lib/utils/router.dart
  lib/videos/curriculum/lecture_screen.dart
  lib/videos/curriculum/roadmap_screen.dart
  lib/videos/curriculum/search_result_screen.dart
Labels: enhancement

#41 챗봇 UI 개선
  lib/chatbot/screens/chatbot_screen.dart
Labels: design
